name: device_info_plus_linux

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    paths:
      - ".github/workflows/device_info_plus_linux.yaml"
      - "device_info_plus_linux/**"
  push:
    branches:
      - main
    paths:
      - ".github/workflows/device_info_plus_linux.yaml"
      - "device_info_plus_linux/**"

jobs:
  build:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/flutter_package.yml@v1
    with:
      flutter_channel: stable
      flutter_version: 3.3.10
      working_directory: device_info_plus_linux

