version: 2
enable-beta-ecosystems: true
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/device_info_plus"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/device_info_plus/example"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/device_info_plus_platform_interface"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/device_info_plus_android"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/device_info_plus_ios"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/device_info_plus_linux"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/device_info_plus_macos"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/device_info_plus_web"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/device_info_plus_windows"
    schedule:
      interval: "daily"