name: device_info_plus_ios
description: iOS implementation of the device_info_plus plugin
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0-366.0.dev <4.0.0"

flutter:
  plugin:
    implements: device_info_plus
    platforms:
      ios:
        pluginClass: DeviceInfoPlusPlugin
        dartPluginClass: DeviceInfoPlusIOS

dependencies:
  flutter:
    sdk: flutter
  device_info_plus_platform_interface:
    path: ../device_info_plus_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  plugin_platform_interface: ^2.0.0
  very_good_analysis: ^3.1.0
