name: device_info_plus_platform_interface
description: A common platform interface for the device_info_plus plugin.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0-366.0.dev <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^3.1.0
